name: EM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      - name: Install dependencies
      run: |
        sudo apt update --quiet -y
        sudo apt install --quiet -y libsdl2-dev
      - name: Verify
        run: emcc -s USE_SDL=2 -o s2main.html s2main.c main02_2.c main02_3.c
